### ISSUE TITLE
Cannot find grade item for 'videotime'

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-mod_videotime#1]
An internal error occurred in the completion system. (System administrators can enable debugging information to see more detail.)

Debug info: Cannot find grade item for 'videotime'
cm '169' matching number '0'
Error code: err_system
Stack trace:
line 1887 of /lib/completionlib.php: moodle_exception thrown
line 828 of /lib/completionlib.php: call to completion_info->internal_systemerror()
line 1492 of /lib/completionlib.php: call to completion_info->internal_get_state()
line 1427 of /lib/completionlib.php: call to completion_info->get_incomplete_data_object()
line 471 of /course/renderer.php: call to completion_info->get_data()
line 922 of /course/renderer.php: call to core_course_renderer->course_section_cm_completion()
line 824 of /course/renderer.php: call to core_course_renderer->course_section_cm()
line 1020 of /course/renderer.php: call to core_course_renderer->course_section_cm_list_item()
line 913 of /course/format/renderer.php: call to core_course_renderer->course_section_cm_list()
line 57 of /course/format/topics/format.php: call to format_section_renderer_base->print_multiple_section_page()
line 288 of /course/view.php: call to require()

**Comment by stefanscholz** [comment]
This bug happens when only video time is installed. (The version from the plugin directory)

The free version displays the completion criteria on grade required, which should of course not be existing in the free version. If someone ticks that checkbox, the course can not be accessed by any non editing user.

**Comment by moodledev** [comment]
![image](https://user-images.githubusercontent.com/46829091/67136479-54df3180-f1ec-11e9-86c3-2d0f67c9f4de.png)
This is what I see with Video Time free.

**Comment by stefanscholz** [comment]
Then apparently it is not the latest version that was installed; I have checked, it's 1.0 (2019071200). I.e. that that has already been fixed. Perfect.
