### ISSUE TITLE
Grade item option to disable and default

### ISSUE THREAD

**Issue by neilstapleton** [stefanscholz/moodle-mod_videotime#10]
Hi @stefanscholz 

Thought I'd log this one as an issue here rather than email you. As we've been rolling out out use of VideoTime we are finding a really issue with gradebook items being added, where in most cases we are no making us of the grading features. So we'd like a way to default that to off, and not have the gradebook item added by default fro all VideoTime instances.

What I'd imagined was to add an option like this, to the Grade settings.

https://images.c43.co/Kk69T.png

I'd then want to see and option in the Video time admin settings (/admin/settings.php?section=modsettingvideotime) to set this to either 'None' or 'Point' by default.

Alternatively it could just be an additional checkbox for 'enable grading' in both settings and admin a setting.

Best wishes
Neil

**Comment by stefanscholz** [comment]
Hi Neil,

That's actually already on our backlog. We'll include an option similar to what you suggested in the next release of videotime. Expect the 1.4 release for summer. The feature will however be available in a 1.3.x release before that and I'll let you know when it is released. (I hope end of June)

Cheers
Stefan

**Comment by neilstapleton** [comment]
Thanks Stefan, that's great.
