### ISSUE TITLE
tracking does not work in Moodle 3.9

### ISSUE THREAD

**Issue by francescopepoli** [stefanscholz/moodle-mod_videotime#15]
Video viewing tracking does not work in Moodle 3.9
Video View Tracking does not work with Moodle 3.9
It only works if I enter the student's ability to track completion
Thank's

**Comment by stefanscholz** [comment]
Hi Francesco,

We'll look into it and keep you posted.

Best
Stefan

**Comment by stefanscholz** [comment]
Dear Francesco,

We‘ve found one issue which could have lead to an issue with the activity completion by view criteria. Can you please update to 1.3.1 and check if the problem is still there? 

Thanks!
Stefan

**Comment by francescopepoli** [comment]
with the update everything is now ok 
Thank's
