### ISSUE TITLE
Failure after install

### ISSUE THREAD

**Issue by nachoporque** [stefanscholz/moodle-mod_videotime#19]
Hi, got the pro version of Videotime, i have installed it in a non production site, all has gone ok but after installation i am not able to add a new activity in my course and i only get the message that there is an error "Invalid user". Please, you help me?

Thanks.

**Comment by stefanscholz** [comment]
Hi! 

Sorry to learn that you have issues on your site. 
I can't think of an error message related to "invalid user" from video time, therefore can you please provide more details, most importantly:
* exact wording of error message, ideally with screenshot
* steps to reproduce error message
* moodle version
* used theme
* videotime version (both mod_videotime as well as mod_videotime_pro)

Thanks!

**Comment by nachoporque** [comment]
Hello,

Thanks for the fast answer.

Attached you can see the message, it is produced when I try to add and activity or resource, but it does not show the list of activities/resources available.

There is an error

Invalid user.


Moodle version: Moodle 3.9.2+ (Build: 20200918)

Theme:
[lambda]

Video Time versions:

[cid:image002.png@01D6A17F.1ECB8060]

[cid:image003.png@01D6A17F.1ECB8060]

[cid:image004.png@01D6A17F.1ECB8060]


It’s quite weird. To be honest as this is a test LMS that i use before instlalling in the production one, it has been a long time since i do not use it and i am not 100% sure what could happen.

I will install a new Moodle, set up the same theme and install your soft so we can see if the problema appears again or no. So if you want wait for my test before diving into the code, i will let you know what happens.


Best regards.

Nacho García

--- AVISO SOBRE CONFIDENCIALIDAD. La legislación española ampara el secreto de las comunicaciones. Este correo electrónico y sus anexos son estrictamente confidenciales. Si Vd. no es el destinatario del mismo, por favor, notifíquenoslo inmediatamente y destruya el original. No deberá copiar este mensaje ni sus anexos o usarlo para propósito alguno, ni divulgar su contenido a ninguna persona.

--- WARNING ABOUT CONFIDENTIALITY. Spanish law guarantees privacy in electronic communications. This message and its attachments are confidential. If you are not the intended recipient please, notify us immediately and destroy the original. You should not copy this message or use it for any purpose, nor disclose its content to any other person.


De: bdecent <notifications@github.com>
Responder a: stefanscholz/moodle-mod_videotime <reply@reply.github.com>
Fecha: martes, 13 de octubre de 2020, 10:51
Para: stefanscholz/moodle-mod_videotime <moodle-mod_videotime@noreply.github.com>
CC: nachoporque <nachoporque@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [stefanscholz/moodle-mod_videotime] Failure after install (#19)


Hi!

Sorry to learn that you have issues on your site.
I can't think of an error message related to "invalid user" from video time, therefore can you please provide more details, most importantly:

  *   exact wording of error message, ideally with screenshot
  *   steps to reproduce error message
  *   moodle version
  *   used theme
  *   videotime version (both mod_videotime as well as mod_videotime_pro)

Thanks!

**Comment by stefanscholz** [comment]
Hi Nacho,

unfortunately do not see any images in your reply.
You can also send them to me directly hello@bdecent.de 

Best
Stefan
