### ISSUE TITLE
VideoTime activities added to gradebook even with grade to pass set to zero

### ISSUE THREAD

**Issue by amwalding** [stefanscholz/moodle-mod_videotime#21]
The result of this issue is that videotime activities are in the gradebook when they should not be.

**Comment by stefanscholz** [comment]
Hi!

Thanks for posting this.
We're aware of that issue and have a fix planned for the next release (1.4).

Best wishes
Stefan

**Comment by stefanscholz** [comment]
Hi!

FYI: we've improved the grade feature in the upcoming video time minor release (1.4.2). If you are interested to try this before the official release, let me know. It's already installed on videotime.bdecent.de. Essentially, unless the teacher checks enables the grade sync, grade items are no longer created.

﻿Thanks
﻿Stefan
