### ISSUE TITLE
Column name is a MSSQL reserved word in 'videotime_session.percent'

### ISSUE THREAD

**Issue by josemariabolanos** [stefanscholz/moodle-mod_videotime#22]
Found running Totara unit tests, we are not using MSSQL but I thought you should know.

**Comment by stefanscholz** [comment]
Dear Jose,

thanks for raising this issue. We'll look into it!
(I think we actually fixed that issue already; which version have you tested?)

Cheers
Stefan

**Comment by josemariabolanos** [comment]
Hi Stefan,

We are using 1.2 Pro.
$plugin->release = '1.2';
$plugin->version = 2019092701;

I don't think we can use 1.3 with our version of Totara, let me know if there's a 1.2+ version we should be using :)

Thanks,
Josemaria

**Comment by stefanscholz** [comment]
Hi Josemaria,

all Video Time versions are tested with Totara 12 and should work just fine.

We officially support the latest two versions of moodle (unless the latest two are no LTS versions, which was the case prior to 3.9 for example, then it would be the latest two versions plus the latest LTS version, in that case 3.5), and the latest version of totara. (however, we haven't finished testing on totara 13 – if you can/want to help with that, please let me know)

Best
Stefan
