### ISSUE TITLE
Video disappears when text is too big

### ISSUE THREAD

**Issue by Carlos-mb** [stefanscholz/moodle-mod_videotime#25]
If you create an activity and add a large text (in my case 4416 chars), the video is not shown. 

I have found that 4416 is te limit in the activity I have used to test.

Regards
Carlos

**Comment by stefanscholz** [comment]
Thanks Carlos for reporting this issue. We will look into it.

Best
Stefan

**Comment by stefanscholz** [comment]
Hi Carlos, 

we fixed that issue in the latest version which will be released soon. If you want to give it a try before the release, let me know! (it's already installed on videotime.bdecent.de)

Best
Stefan
