### ISSUE TITLE
 Embed student ID

### ISSUE THREAD

**Issue by samuelPsicos** [stefanscholz/moodle-mod_videotime#8]
Hi there
Would there be a way to embed a watermark in the video with the data of the student who is watching the video?

I attach an image
thanks
![ID number vimeo](https://user-images.githubusercontent.com/63096050/78358118-f26bc900-75b2-11ea-8801-1922df538fec.png)

**Comment by stefanscholz** [comment]
Dear Samuel,

I doubt it is possible to add it "into" the video. We could theoretically create an overlay on top of the video though; it would seem to be in the video.

If you are looking for a way to protect your videos, please be aware that using simple tools, a video can easily be downloaded. I.e. if somebody wants to get the video, he/she can. An overlay on top of the video would only help for people who do not know how to download the video.

Please let me know what you think.
Stefan

**Comment by samuelPsicos** [comment]
if I had thought of something.

but if the video is embedded in moodle from vimeo, which already has its viewing restrictions ONLY in moodle.

and in moodle the options of right-clicking or opening on another screen have been disabled, therefore you have no choice but to see it within the platform.

But by adding your student ID, recording is avoided by programs like "camtasia studio or filmora"
is to make it more difficult to misuse it and that is why it is not worth doing ...

thank you very much friend

**Comment by stefanscholz** [comment]
Hi Samuel,

ok, I understand.
Let me check with my developer and get back to you.

Cheers
Stefan

**Comment by stefanscholz** [comment]
Dear Samuel,

sorry for the long waiting time.
We've discussed this internally and can confirm that we can do this if funding is provided.

If you are interested, let me know via email (hello@bdecent.de) and I'll provide the details.

Best
Stefan

**Comment by samuelPsicos** [comment]
Hola.

Cuanto necesitarían para desarrollar el proyecto?

un  saludo

**Comment by stefanscholz** [comment]
Dear Samuel,

assuming that you are asking for the efforts – we're looking at approx. a day of work.
If you are interested, let me know via email (hello@bdecent.de) and I'll provide the details.

Best
Stefan

**Comment by samuelPsicos** [comment]
hola.

Saben ya cuanto necesitarían para desarrollar el proyecto?
