### ISSUE TITLE
For Moodle Mobile App

### ISSUE THREAD

**Issue by takahashi8181** [stefanscholz/moodle-mod_videotime#9]
Hi, 
Is there any plan for moodle mobile app compatible?

**Comment by stefanscholz** [comment]
Yes. It's already implemented in the upcoming version 1.3 of video time pro.

Development is complete, final testing currently ongoing. Expect release this week. 

You can test it on videotime.bdecent.de immediately - the app is enabled for that site.

**Comment by argwallace** [comment]
Will this be a Pro only option or will the free version also work? Thanks!

**Comment by stefanscholz** [comment]
Hi! App support is available in pro only.

**Comment by argwallace** [comment]
Any plans to include this function in the Basic version? We just need the basic functionality for our non-profit for the occasional user who might use the Mobile App. Thanks for your time and work. Best Regards. Stephen

**Comment by stefanscholz** [comment]
Maybe sometime. But we do have special deals for non profits - send me an email with a link to your organisation and I'll have a look!
